# Generated by Django 4.1.4 on 2022-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor_code", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in stock", "В наличии"),
                            ("on order", "Под заказ"),
                            ("receipt expected", "Ожидается поступление"),
                            ("not available", "Нет в наличии"),
                            ("not produced", "Не производится"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="media/images/product")),
            ],
        ),
    ]
