# Generated by Django 4.1.4 on 2022-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor_code",
            field=models.IntegerField(db_index=True),
        ),
    ]
